### ISSUE TITLE
Running behind another reverse proxy results in a 301 loop

### ISSUE THREAD

**Issue by emichael** [linuxserver/docker-mastodon#5] opened 2022-11-10 22:03 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Starting an image with `LOCAL_DOMAIN=foo.org` and running a separate NGINX proxy with

```
server {
	listen 443 ssl;
	server_name	foo.org;

	# SSL PARAMS

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection $connection_upgrade;

	location / {
		proxy_pass	http://X.X.X.X:YYYY;
	}
}
```

should serve the server. Here, X.X.X.X is the IP address of the docker host and the Mastodon image was started with `-p YYYY:80`.

Additionally, the image should probably support the `TRUSTED_PROXY_IP` Mastodon variable. I'm not sure that it does given that the nginx config has `proxy_set_header Proxy ""`. The 301 loop happens whether or not `TRUSTED_PROXY_IP` is set, though.

## Current Behavior
There's a 301 redirection loop for `https://foo.org`

**Comment by thespad** [comment] 2022-11-10 23:12
Although we removed it from the nginx configuration, it looks like there's a forced redirect to https somewhere else within the application and that's what'll be causing your redirect loop because you're pointing at port 80. Will probably have to update the readme.

**Comment by emichael** [comment] 2022-11-10 23:29
Yes, that was it. If I manually set `proxy_set_header X-Forwarded-Proto https;` in the image's nginx config, it works. I'm not sure what the proper way to run an NGINX proxy behind an NGINX proxy is.

**Comment by aptalca** [comment] 2022-11-10 23:53
Fwiw, this is the conf I'm using with SWAG: https://github.com/linuxserver/reverse-proxy-confs/pull/507/files

**Comment by eric-pierce** [comment] 2022-11-13 23:25
I'm running into a possibly related issue with Traefik - I get "400 Bad Request The plain HTTP request was sent to HTTPS port" from the container nginx install when visiting my domain

**Comment by thespad** [comment] 2022-11-14 09:05
Mastodon has an internal redirect to the https public URL of your instance, which means you need to proxy with the correct protocol (or the right headers) or you'll get a redirect loop.

```yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.mastodon-all.rule=Host(`mastodon.example.com`)
      - traefik.http.routers.mastodon-all.entrypoints=https,http
      - traefik.http.routers.mastodon-all.service=mastodon-svc
      - traefik.http.services.mastodon-svc.loadbalancer.server.scheme=https
      - traefik.http.services.mastodon-svc.loadbalancer.server.port=443
```
Or thereabouts.

**Comment by eric-pierce** [comment] 2022-11-14 17:31
Thanks @thespad  and @cooperaj  for the replies. I do have those traefik labels configured,  the relevant pieces of my docker-compose file are below. I'm actually getting a 500 internal error with the below configuration, and Traefik is reporting:

`time="2022-11-14T11:27:43-06:00" level=debug msg="'500 Internal Server Error' caused by: x509: cannot validate certificate for 10.10.20.5 because it doesn't contain any IP SANs`

docker-compose:
`
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
        # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --api=false
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`, `$MAST_DOMAIN`)
      - --entrypoints.https.http.tls.domains[0].main=$DOMAINNAME
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME
      - --entrypoints.https.http.tls.domains[1].main=$MAST_DOMAIN # Pulls main cert for second domain
      - --entrypoints.https.http.tls.domains[1].sans=*.$MAST_DOMAIN # Pulls wildcard cert for second domain
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=5
    networks:
      - traefik
      - socket-proxy
    security_opt:
      - no-new-privileges:true
    secrets:
      - cloudflare_email
      - cloudflare_api_key
    depends_on:
      - socket-proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - $DOCKERDIR/traefik2/rules:/rules
      - $DOCKERDIR/traefik2/acme/acme.json:/acme.json
      - $DOCKERDIR/traefik2/traefik.log:/traefik.log
      - $DOCKERDIR/shared:/shared
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - CF_API_EMAIL_FILE=/run/secrets/cloudflare_email
      - CF_API_KEY_FILE=/run/secrets/cloudflare_api_key
    labels:
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[1].main=$MAST_DOMAIN"
      - "traefik.http.routers.traefik-rtr.tls.domains[1].sans=*.$MAST_DOMAIN"
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file"

  mastodon:
    container_name: mastodon
    image: linuxserver/mastodon:latest
    restart: always
    networks:
      - traefik
      - internal
    depends_on:
      - traefik
      - postgres
      - redis
    ports:
      - 8008:80
      - 8443:443
    volumes:
      - $DOCKERDIR/mastodon:/config
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - LOCAL_DOMAIN=$MAST_DOMAIN
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=$MAST_POSTGRES_PASSWORD
      - DB_PORT=5432
      - ES_ENABLED=false
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - OTP_SECRET=$OTP_SECRET
      - VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY
      - VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY
      - SMTP_SERVER=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - SMTP_LOGIN=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - SMTP_FROM_ADDRESS=$SMTP_FROM
      - S3_ENABLED=false
      #- WEB_DOMAIN=$MAST_DOMAIN #optional
      #- RAILS_SERVE_STATIC_FILES=true
      #- ES_HOST=es #optional
      #- ES_PORT=9200 #optional
      #- ES_USER=elastic #optional
      #- ES_PASS=elastic #optional
      #- S3_BUCKET= #optional
      #- AWS_ACCESS_KEY_ID= #optional
      #- AWS_SECRET_ACCESS_KEY= #optional
      #- S3_ALIAS_HOST= #optional
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.mastodon-rtr.entrypoints=https,http"
      - "traefik.http.routers.mastodon-rtr.rule=Host(`$MAST_DOMAIN`)"
      - "traefik.http.routers.mastodon-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.mastodon-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.mastodon-rtr.service=mastodon-svc"
      - "traefik.http.services.mastodon-svc.loadbalancer.server.port=443"
      - "traefik.http.services.mastodon-svc.loadbalancer.server.scheme=https"
 `

**Comment by mark-monteiro** [comment] 2022-11-20 00:03
I would love some help getting this to work with Caddy. The config I'm using below in my Caddyfile fails with a 502 response.

```txt
mastadon.example.com {
        reverse_proxy https://localhost:8882
}
```

8882 is the https port I have exposed from the Mastadon docker image with the following in my `docker-compose.yml`

```yml
    ports:
      - 8882:443
```

Is there something obvious I'm missing here? Or any tips on how I could diagnose what's going wrong?

**Comment by thelittlemike** [comment] 2022-11-21 22:52
Was this ever resolved? I have been absolutely stuck on this. My environment is slightly different as I run this in unRAID, but I've either gotten a graphic of an elephant and an error message saying "We're sorry, but something went wrong on our end." and then I get an error message in the logs about ip_blocks and Google tells me that's a failed database migration but this is a new install.

**Comment by thespad** [comment] 2022-11-21 23:07
That sounds like a completely unrelated issue. I'm going to close this as it's become a dumping ground for miscellaneous connection problems.

If you have specific problems with the image, please open a new issue and provide the information requested by the issue template.

**Closed by thespad** 2022-11-21 23:07 UTC

**Comment by emichael** [comment] 2022-11-21 23:11
@thespad To be clear my original issue remains, and I described a potential workaround but not an actual fix. This image remains broken when running behind another reverse proxy.

**Comment by thespad** [comment] 2022-11-21 23:16
It's not broken, mastodon forces a redirect to the https URL of your local domain (or web domain if set), it's not something we're doing. You cannot proxy the http port without additional external configuration to support it.

When I have time I'll update the readme to clarify this as people seem to be struggling with configuring their reverse proxy setups for https backend services.

**Comment by emichael** [comment] 2022-11-21 23:30
Yes, it is. The NGINX config generated by default in the image resets the `X-Forwarded-Proto` header sent to it [here](https://github.com/linuxserver/docker-mastodon/blob/main/root/defaults/nginx/site-confs/default.conf.sample#L102) and [here](https://github.com/linuxserver/docker-mastodon/blob/main/root/defaults/nginx/site-confs/default.conf.sample#L121). You have to do something [like this](https://stackoverflow.com/questions/21230918/nginx-scheme-variable-behind-load-balancer/21911864#21911864) to set it based on the `X-Forwarded-Proto` passed in or simply not set any of those headers at all inside the image.

**Comment by aptalca** [comment] 2022-11-21 23:43
It's not broken. We are reverse proxying our team instance via SWAG (our nginx based reverse proxy solution). You just need to set it correctly with the necessary headers.

Here's the SWAG proxy conf we're using:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/mastodon.subdomain.conf.sample
And here's the proxy.conf included in there:
https://github.com/linuxserver/docker-swag/blob/master/root/defaults/nginx/proxy.conf.sample

**Comment by thespad** [comment] 2022-11-22 09:55
The nginx conf used by the container is sourced from the official implementation https://github.com/mastodon/mastodon/blob/main/dist/nginx.conf with a couple of tweaks for the path routing based on how the container is set up.

**Comment by TangentFoxy** [comment] 2023-07-07 00:36
> Here's the SWAG proxy conf we're using: https://github.com/linuxserver/reverse-proxy-confs/blob/master/mastodon.subdomain.conf.sample

Tried using that config, doesn't work. Dunno what I'm doing wrong. (Am using different ports, but as long as they match, shouldn't have an effect..)
